#!/bin/bash
print=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p) print=true ;;
    --print) print=true ;;
  esac
  shift
done

source .env

sql=$(cat <<EOF
CREATE USER IF NOT EXISTS '$WIKI_DB_SCHEMA_USER'@'%' IDENTIFIED BY '$WIKI_DB_SCHEMA_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX ON $DATABASE_NAME.* TO '$WIKI_DB_SCHEMA_USER'@'%';

CREATE USER IF NOT EXISTS '$WIKI_DB_APP_USER'@'%' IDENTIFIED BY '$WIKI_DB_APP_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON $DATABASE_NAME.* TO '$WIKI_DB_APP_USER'@'%';
EOF
)

if $print; then
  cat <<EOF
CREATE USER IF NOT EXISTS '$WIKI_DB_SCHEMA_USER'@'%' IDENTIFIED BY '$WIKI_DB_SCHEMA_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX ON $DATABASE_NAME.* TO '$WIKI_DB_SCHEMA_USER'@'%';

CREATE USER IF NOT EXISTS '$WIKI_DB_APP_USER'@'%' IDENTIFIED BY '$WIKI_DB_APP_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON $DATABASE_NAME.* TO '$WIKI_DB_APP_USER'@'%';
EOF
else
  mariadb -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE USER IF NOT EXISTS '$WIKI_DB_SCHEMA_USER'@'%' IDENTIFIED BY '$WIKI_DB_SCHEMA_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX ON $MYSQL_DATABASE.* TO '$WIKI_DB_SCHEMA_USER'@'%';

CREATE USER IF NOT EXISTS '$WIKI_DB_APP_USER'@'%' IDENTIFIED BY '$WIKI_DB_APP_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON $MYSQL_DATABASE.* TO '$WIKI_DB_APP_USER'@'%';
EOF
fi
