services:
  mediawiki:
    image: mediawiki:1.45
    container_name: mediawiki_app
    profiles:
     - dev
     - prod
    restart: always
    ports:
      - 8080:80
    volumes:
      - mediawiki_images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      MEDIAWIKI_DB_HOST: ${DATABASE_HOST}
      MEDIAWIKI_DB_USER: ${WIKI_DB_APP_USER}
      MEDIAWIKI_DB_PASSWORD: ${WIKI_DB_APP_PASSWORD}
      MEDIAWIKI_DB_NAME: ${DATABASE_NAME}

  db:
    image: mariadb:11.8
    container_name: mediawiki_db
    profiles: 
     - dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      WIKI_DB_SCHEMA_USER: ${WIKI_DB_SCHEMA_USER}
      WIKI_DB_SCHEMA_PASSWORD: ${WIKI_DB_SCHEMA_PASSWORD}
      WIKI_DB_APP_USER: ${WIKI_DB_APP_USER}
      WIKI_DB_APP_PASSWORD: ${WIKI_DB_APP_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./create_users.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  mediawiki_images:
  db_data:
